name: check on push

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      
      - name: Install poetry
        run: pip install poetry
      
      - name: Install
        run: make install
        
      - name: Lint
        run: make lint
        
